### ISSUE TITLE
Rename injector to "Sexually unified" for gays and other genders in mind

### ISSUE THREAD

**Issue by Thesourtimes** [Cumcord/Impregnate#4]
As you all know there are people other than heterosexuals out there and males can cum to other places other than a woman's vagena freely in this modern era. For the straights and other genders (pansexual, bisexual etc.) name of this injector should be changed into something like "sexing", "sexually unified" or "bed". I hope cumcord and It's staff is open-minded and LGBTQI+ friendly.

**Comment by Thesourtimes** [comment]
Also as a note future projects can be named after things like pegging and dildo for womans and other not genders without a penis.

**Comment by lexisother** [comment]
90% of our staff sucks dick.

**Comment by E-boi** [comment]
Idk about you but impregnate sounds funnier then "sexing" or "bed"

**Comment by Thesourtimes** [comment]
As a sexual experience your administration should let your's staff to experience BDSM and pegging for remembrance of sexual equality. I hope we will beat this reactionary male-supremacist system in future. From a LGBTQI+ trans furry black developer.

**Comment by E-boi** [comment]
The fuck

**Comment by lexisother** [comment]
sounds like a skill issue to me.

**Comment by Cr3atable** [comment]
sounds like a skill issue to me
