### ISSUE TITLE
no longer works

### ISSUE THREAD

**Issue by neverExisted** [Cumcord/Impregnate#8]
i cannot impregnate discord (windows 11)

**Comment by xirreal** [comment]
cope harder

**Comment by maisymoe** [comment]
i agree with the statement above

**Comment by lexisother** [comment]
i agree with the statement above my own

**Comment by neverExisted** [comment]
remember to shave your neckbeards

**Comment by lexisother** [comment]
remember to kiss your mom with that mouth
