### ISSUE TITLE
:trollface: part 2

### ISSUE THREAD

**Issue by nyakowint** [Cumcord/Impregnate#9]
discord had an abortian woaaaah

**Comment by twnlink** [comment]
yeah

**Comment by lexisother** [comment]
@ItzOnlyAnimal fix it fucking fix @ItzOnlyAnimal FIX THE DISCORE IT DOESN'T @ItzOnlyAnimal WORK @ItzOnlyAnimal @ItzOnlyAnimal

**Comment by nyakowint** [comment]
NOOOO :trollface: =€=~{¥€}|}®[¥✓`}©\®}¢

**Comment by phorcys420** [comment]
whazt

**Comment by nyakowint** [comment]
whazt

**Comment by nyakowint** [comment]
nuh uh
